// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-dossiers.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_dossiers_default = defineTool({
  name: "list_dossiers",
  title: "Lister les dossiers commerciaux",
  description: "Liste les dossiers commerciaux visibles par l'utilisateur connect\xE9 (Arcade OS). Renvoie id, titre, client, statut et date de mise \xE0 jour.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Nombre max de dossiers (d\xE9faut 20)."),
    statut: z.string().optional().describe("Filtre optionnel par statut exact.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, statut }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("dossiers").select("id, titre, client_nom, statut, updated_at").order("updated_at", { ascending: false }).limit(limit ?? 20);
    if (statut) q = q.eq("statut", statut);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { dossiers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-catalog.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var search_catalog_default = defineTool2({
  name: "search_catalog",
  title: "Rechercher dans le catalogue produits",
  description: "Recherche des produits actifs dans le catalogue Arcade OS par nom ou cat\xE9gorie (bornes d'arcade, flippers, etc.).",
  inputSchema: {
    query: z2.string().trim().min(1).describe("Terme de recherche (nom ou cat\xE9gorie du produit)."),
    limit: z2.number().int().min(1).max(50).optional().describe("Nombre max de r\xE9sultats (d\xE9faut 15).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const { data, error } = await supabase.from("catalog_products").select("id, name, category, price, description").eq("active", true).or(`name.ilike.%${query}%,category.ilike.%${query}%`).limit(limit ?? 15);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-prospects.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_prospects_default = defineTool3({
  name: "list_prospects",
  title: "Lister les prospects",
  description: "Liste les prospects visibles par l'utilisateur (module Prospection). Filtre optionnel par statut ou segment.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Nombre max (d\xE9faut 25)."),
    statut: z3.string().optional().describe("Statut kanban (ex: 'nouveau', 'contacte', 'chaud')."),
    segment: z3.string().optional().describe("Segment: 'loisirs', 'chr', 'retail'...")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, statut, segment }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9." }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let q = supabase.from("prospects").select(
      "id, entreprise, contact_nom, segment, statut, adresse, lgm_status, pret_a_envoyer, created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 25);
    if (statut) q = q.eq("statut", statut);
    if (segment) q = q.eq("segment", segment);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { prospects: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "yhfghipueqfkgysaulvl";
var mcp_default = defineMcp({
  name: "arcade-os-mcp",
  title: "Arcade OS",
  version: "0.1.0",
  instructions: "Outils Arcade OS (Avranches Automatic) : lister les dossiers commerciaux, chercher dans le catalogue produits, lister les prospects. Chaque appel s'ex\xE9cute au nom de l'utilisateur connect\xE9 (RLS Supabase).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_dossiers_default, search_catalog_default, list_prospects_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
