ALTER TABLE public.veille_jobs ADD COLUMN IF NOT EXISTS progress INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.gaia_revues ADD COLUMN IF NOT EXISTS progress INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.gaia_revues ADD COLUMN IF NOT EXISTS etape TEXT;